import React,{useEffect,useState} from 'react'
import {motion} from 'framer-motion'
import {Link} from 'react-router-dom'
import {ArrowRight,ArrowUpRight,BrainCircuit,Database,ChartNoAxesCombined,CloudCog,UsersRound,Settings2,ServerCog,Workflow,ScanSearch,MapPinned,ShieldCheck} from 'lucide-react'
import {clients} from '../data/siteData'
const stories=[['Enterprise technology,','engineered for impact.','KramaTek brings AI, data, cloud and digital engineering together to modernize operations, accelerate decisions and build resilient digital capabilities.'],['Build intelligence','into the business.','Connect data, AI and automation directly to the workflows, systems and teams where decisions happen.'],['Modern platforms.','Smarter operations.','From cloud-native applications to operational AI, we design systems that are easier to scale, observe and evolve.']]
const svc=[[BrainCircuit,'AI Solutions','GenAI, RAG, agentic AI, computer vision and governed AI workflows.','/services/ai-solutions'],[Database,'Data Engineering','Modern pipelines, platforms, integration, quality and observability.','/services/data-engineering'],[ChartNoAxesCombined,'Analytics & Intelligence','BI, predictive analytics, anomaly detection and decision intelligence.','/services/analytics-intelligence'],[CloudCog,'Digital Transformation','Cloud, application modernization, digital experience and automation.','/services/digital-transformation'],[UsersRound,'Staff Augmentation','Specialized engineering, architecture, AI, cloud and data talent.','/services/staff-augmentation'],[Settings2,'Managed Services','Operate, monitor and continuously improve critical digital platforms.','/services/managed-services']]
export default function Home(){const [idx,setIdx]=useState(0);useEffect(()=>{const t=setInterval(()=>setIdx(v=>(v+1)%stories.length),5500);return()=>clearInterval(t)},[]);const [a,b,c]=stories[idx];return <>
<section className="hero"><div className="container hero-grid"><div className="hero-copy"><div className="hero-pill">GLOBAL ENTERPRISE TECHNOLOGY</div><motion.div key={idx} initial={{opacity:0,y:15}} animate={{opacity:1,y:0}}><h1>{a}<br/><span>{b}</span></h1><p>{c}</p></motion.div><div className="hero-actions"><Link className="btn primary" to="/platform">Explore Solutions <ArrowRight size={17}/></Link><Link className="btn ghost" to="/contact">Talk to an Expert</Link></div><div className="story-dots">{stories.map((_,i)=><button key={i} onClick={()=>setIdx(i)} className={i===idx?'active':''}/>)}</div></div><div className="enterprise-map"><div className="map-head"><span>ENTERPRISE INTELLIGENCE FABRIC</span><b>LIVE</b></div><div className="map-flow"><div className="col"><label>DATA & EVENTS</label><div><Database/>Enterprise Data</div><div><ServerCog/>Systems & APIs</div><div><ScanSearch/>Video & Sensors</div></div><div className="arrows">→<br/>→<br/>→</div><div className="core"><BrainCircuit/><strong>KRAMA</strong><small>AI + DATA + RULES</small></div><div className="arrows">→<br/>→<br/>→</div><div className="col"><label>ACTIONS</label><div><ChartNoAxesCombined/>Insights</div><div><Workflow/>Automation</div><div><ShieldCheck/>Decisions</div></div></div><div className="map-foot"><span>Context-aware</span><span>Governed</span><span>Observable</span><span>Integrated</span></div></div></div></section>
<section className="clients"><div className="container"><div className="client-label">ORGANIZATIONS WE SUPPORT</div><div className="client-grid">{clients.map((x,i)=><div className="client-logo" key={i}><img src={`/assets/${x}`} alt="Client"/></div>)}</div></div></section>
<section className="section offer"><div className="container"><div className="section-head centered"><div><div className="eyebrow">WHAT WE OFFER</div><h2>Enterprise services that move<br/>from strategy to production.</h2><p>One technology partner across AI, data, applications, cloud and operations.</p></div></div><div className="cards">{svc.map(([Icon,t,d,p],i)=><motion.article className="service-card" key={t} whileHover={{y:-8}}><Icon/><span className="card-num">0{i+1}</span><h3>{t}</h3><p>{d}</p><Link to={p}>Explore service <ArrowUpRight size={15}/></Link></motion.article>)}</div></div></section>
<section className="section dark"><div className="container intelligence"><div><div className="eyebrow light">FROM SIGNAL TO ACTION</div><h2>Build intelligence into<br/>the operating model.</h2><p>Connect operational data, enterprise knowledge, AI models and workflow automation to create systems that help teams decide and act.</p></div><div className="stack">{[[Workflow,'AI Command & Control','Events → Prioritization → Incident → Response'],[BrainCircuit,'Enterprise Knowledge AI','Knowledge → Retrieval → Reasoning → Action'],[ScanSearch,'Vision Intelligence','Video → Detection → Context → Alert'],[MapPinned,'Geospatial Intelligence','Imagery → Change → Location → Decision']].map(([Icon,t,d])=><div className="stack-card" key={t}><Icon/><div><h3>{t}</h3><p>{d}</p></div><ArrowRight/></div>)}</div></div></section>
<section className="tech"><div className="container"><div className="section-head centered"><div><div className="eyebrow">TECHNOLOGY ECOSYSTEM</div><h2>Modern platforms. Open architecture.</h2><p>Designed around the stack that best fits the problem—not a single vendor.</p></div></div><div className="tech-grid">{['AWS','Microsoft Azure','Google Cloud','Snowflake','Databricks','Kubernetes','MongoDB','OpenAI'].map(x=><div key={x}>{x}</div>)}</div><small>Technology ecosystem shown for architectural capability and compatibility; not a statement of formal partnership.</small></div></section>
<section className="section process"><div className="container"><div className="section-head"><div><div className="eyebrow">HOW WE DELIVER</div><h2>Enterprise rigor.<br/>Startup speed.</h2></div><p>Focused delivery from problem definition through production, with architecture, security, observability and ownership built in.</p></div><div className="steps four">{[['Discover','Clarify outcomes, users, systems, constraints and success criteria.'],['Design','Shape architecture, data flows, controls and user experience.'],['Prototype','Validate the riskiest assumptions with a focused working solution.'],['Scale','Productionize with security, observability, resilience and support.']].map(([t,d],i)=><div className="step" key={t}><span>0{i+1}</span><h3>{t}</h3><p>{d}</p></div>)}</div></div></section>
<section className="cta-section"><div className="container cta-box"><div><div className="eyebrow light">LET'S BUILD WHAT'S NEXT</div><h2>Turn a complex technology problem into a production capability.</h2><p>Bring us the business challenge. We’ll help shape the architecture, delivery path and engineering needed to move it forward.</p></div><Link className="btn gold" to="/contact">Start a Conversation <ArrowRight size={17}/></Link></div></section>
</>}
