
import React,{useEffect,useState} from 'react'
import {motion,AnimatePresence} from 'framer-motion'
import {NavLink} from 'react-router-dom'
import {ArrowRight,ArrowUpRight,BrainCircuit,Database,ChartNoAxesCombined,CloudCog,UsersRound,Settings2,Landmark,RadioTower,HeartPulse,Building2} from 'lucide-react'
import {heroStories,services,clients,industries,insights} from '../data/siteData'
const icons={'ai-solutions':BrainCircuit,'data-engineering':Database,'analytics-intelligence':ChartNoAxesCombined,'digital-transformation':CloudCog,'staff-augmentation':UsersRound,'managed-services':Settings2}
const industryIcons={government:Landmark,telecom:RadioTower,healthcare:HeartPulse,'financial-services':Building2,enterprise:Building2}
export default function Home(){const [slide,setSlide]=useState(0);useEffect(()=>{const id=setInterval(()=>setSlide(v=>(v+1)%heroStories.length),5600);return()=>clearInterval(id)},[]);const s=heroStories[slide];return <>
<section className="hero"><AnimatePresence mode="wait"><motion.img key={slide} className="hero-image" src={s.image} alt="" initial={{opacity:0,scale:1.02}} animate={{opacity:1,scale:1}} exit={{opacity:0}} transition={{duration:.8}}/></AnimatePresence><div className="hero-overlay"/><div className="container hero-content"><div className="hero-copy"><div className="hero-kicker">{s.eyebrow}</div><AnimatePresence mode="wait"><motion.div key={slide} initial={{opacity:0,y:14}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}}><h1>{s.title}<br/><em>{s.accent}</em></h1><p>{s.text}</p></motion.div></AnimatePresence><div className="hero-actions"><NavLink className="btn primary" to="/platform">Explore Solutions <ArrowRight size={17}/></NavLink><NavLink className="btn secondary" to="/contact">Talk to an Expert</NavLink></div><div className="hero-dots">{heroStories.map((_,i)=><button key={i} className={slide===i?'active':''} onClick={()=>setSlide(i)} aria-label={`Slide ${i+1}`}/>)}</div></div></div></section>
<section className="client-zone"><div className="client-title">ORGANIZATIONS WE SUPPORT</div><div className="marquee"><div className="marquee-track">{[...clients,...clients].map((c,i)=><div className="client-card" key={i}><img src={c.image} alt={c.name}/></div>)}</div></div></section>
<section className="section services-section"><div className="container"><div className="section-heading centered"><div className="eyebrow">WHAT WE OFFER</div><h2>Enterprise services from strategy to production.</h2><p>One technology partner across AI, data, applications, cloud and operations.</p></div><div className="service-grid">{Object.entries(services).map(([slug,v],i)=>{const Icon=icons[slug];return <motion.article className="service-card" key={slug} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}}><a className="service-visual" href={`/services/${slug}`}><img src={v.cardImage} alt={`${v.title} visual`}/></a><div className="service-body"><div className="service-icon"><Icon size={29}/></div><span className="service-no">0{i+1}</span><h3>{v.title}</h3><p>{v.description}</p><a className="service-link" href={`/services/${slug}`}>Explore service <ArrowUpRight size={15}/></a></div></motion.article>})}</div></div></section>
<section className="section industries-section"><div className="container"><div className="section-heading"><div><div className="eyebrow">INDUSTRIES</div><h2>Deep technology. Industry context.</h2></div><p>Architecture is shaped around users, workflows, risk, scale, data and the operating environment.</p></div><div className="industry-grid">{Object.entries(industries).map(([slug,v],i)=>{const Icon=industryIcons[slug];return <a className="industry-card" href={`/industries/${slug}`} key={slug}><img src={v.image} alt=""/><div><Icon/><span>0{i+1}</span><h3>{v.title}</h3><p>{v.description}</p><b>Explore industry →</b></div></a>})}</div></div></section>
<section className="section insights-home"><div className="container"><div className="section-heading"><div><div className="eyebrow">INSIGHTS</div><h2>Ideas for practical enterprise intelligence.</h2></div><NavLink className="text-link" to="/insights">View all insights →</NavLink></div><div className="insight-grid">{insights.map(x=><NavLink className="insight-card" key={x.slug} to={`/insights/${x.slug}`}><img src={x.image} alt=""/><div><span>{x.category}</span><h3>{x.title}</h3><p>{x.summary}</p><b>Read insight →</b></div></NavLink>)}</div></div></section>
<section className="cta-section"><div className="container cta"><div><div className="eyebrow light">LET'S BUILD WHAT'S NEXT</div><h2>Turn a complex technology problem into a production capability.</h2><p>Bring us the business challenge. We’ll help shape the architecture and delivery path.</p></div><NavLink className="btn gold" to="/contact">Start a Conversation <ArrowRight size={17}/></NavLink></div></section>
</>}
